---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-demo
  namespace: dev
  annotations:
    flux.weave.works/tag.podinfod: v4-subscription-service
    flux.weave.works/automated: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: metrics-server
        image: quay.io/brice/metrics-demo:master-a1560c8
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

